pipeline {
  agent {
    kubernetes {
        label 'kaniko-build-agent'
        yaml """
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: jnlp
    workingDir: /home/jenkins/agent/
  - name: kaniko
    workingDir: /home/jenkins/agent/
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "512m"
        memory: "1024Mi"
        ephemeral-storage: "4096Mi"
      limits:
        cpu: "1000m"
        memory: "4096Mi"
        ephemeral-storage: "14Gi"
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: rencibuild-imagepull-secret
          items:
            - key: .dockerconfigjson
              path: config.json
"""
        }
    }
    stages {
        stage('Build') {
            environment {
                PATH = "/busybox:/kaniko:$PATH"
                DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
                DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
            }
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    sh '''#!/busybox/sh
                        /kaniko/executor --dockerfile ./docker/conda-layer/Dockerfile \
                                         --context ./docker/conda-layer/ \
                                         --verbosity debug \
                                         --destination helxplatform/conda-layer:develop-v0.0.8 \
                                         --destination helxplatform/conda-layer:develop-latest

                        '''
                }
            }
        }
        //stage('Test') {
        //    steps {
        //        container('agent-docker') {
        //            sh '''
        //            echo test
        //            '''
        //        }
        //    }
        //}
        //stage('Publish') {
        //    environment {
        //        DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
        //        DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
        //    }
        //    steps {
        //        container('agent-docker') {
        //            sh '''
        //            echo publish
        //            echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin $DOCKER_REGISTRY
        //            docker push helxplatform/nginx:$BRANCH_NAME
        //            '''
        //        }
        //    }
        //}
    }
}
